[versions]
agp = "8.5.0"
leanback = "1.0.0"
glide = "4.11.0"
appcompat = "1.7.0"
material = "1.12.0"
video = "1.0.0"

[libraries]
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
video = { group = "com.google.android.mediahome", name = "video", version.ref = "video" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

